# Generated by Django 3.0.3 on 2020-02-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Panino",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                ("descrizione", models.TextField(verbose_name="descrizione")),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=4, verbose_name="prezzo")),
                ("inserimento", models.DateTimeField(auto_now_add=True, null=True, verbose_name="giorno inserimento")),
                ("disponibilita", models.DateTimeField(null=True, verbose_name="giorno disponibilità")),
            ],
            options={"verbose_name": "panino", "verbose_name_plural": "panini",},
        ),
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("studente", models.CharField(max_length=500, verbose_name="studente")),
                ("classe", models.CharField(max_length=6, verbose_name="classe")),
                ("inserimento", models.DateTimeField(auto_now_add=True, verbose_name="inserimento")),
                ("ritiro", models.DateField(verbose_name="giorno ritiro")),
                ("panini", models.ManyToManyField(to="panino.Panino", verbose_name="panini")),
            ],
            options={"verbose_name": "prenotazione", "verbose_name_plural": "prenotazioni",},
        ),
    ]
